# SELECT 
#     T.YEAR, T.MONTH, T.GENDER, COUNT(T.USERS) AS USERS
#   FROM 
#     (
#         SELECT DISTINCT
#             YEAR(O.SALES_DATE) AS YEAR
#             , MONTH(O.SALES_DATE) AS MONTH
#             , U.GENDER
#             , U.USER_ID AS USERS
#           FROM ONLINE_SALE AS O
#           LEFT JOIN USER_INFO AS U 
#             ON O.USER_ID = U.USER_ID
#          WHERE U.GENDER IS NOT NULL        
#     ) AS T
#  GROUP BY T.YEAR, T.MONTH, T.GENDER
#  ORDER BY T.YEAR, T.MONTH, T.GENDER

SELECT 
    YEAR(O.SALES_DATE) AS YEAR
    , MONTH(O.SALES_DATE) AS MONTH
    , U.GENDER AS GENDER
    , COUNT(DISTINCT U.USER_ID) AS USERS
  FROM ONLINE_SALE AS O
  LEFT JOIN USER_INFO AS U
    ON O.USER_ID = U.USER_ID
 GROUP BY YEAR, MONTH, GENDER
HAVING U.GENDER IS NOT NULL