WITH RECURSIVE H AS (
    SELECT 0 AS RNUM
    UNION ALL
    SELECT RNUM + 1 FROM H
    WHERE RNUM < 23
)
SELECT H.RNUM, COUNT(ANI.ANIMAL_ID) AS COUNT
  FROM H
  LEFT JOIN 
    ( 
        SELECT 
            HOUR(DATETIME) AS HOUR
            , ANIMAL_ID
          FROM ANIMAL_OUTS
    ) AS ANI
    ON H.RNUM = ANI.HOUR
 GROUP BY H.RNUM
 ORDER BY H.RNUM